OBJS = tee_secpu_fw_load.o ../lib/tee_secpu_fw_loader.o

ifeq ($(ARCH), arm64)
TEEC_EXPORT=$(TDK_DIR)/ca_export_arm64
endif

ifeq ($(ARCH), arm)
TEEC_EXPORT=$(TDK_DIR)/ca_export_arm
endif

CFLAGS += -Wall -I../ta/include -I$(TEEC_EXPORT)/include -I./include -I../lib/include
#Add/link other required libraries here
LDADD += -lteec -L../lib

BINARY=tee_secpu_fw_load

.PHONY: all
all: $(BINARY)

$(BINARY): $(OBJS)
	$(CC) $(LDADD) -o $@ $^

.PHONY: clean
clean:
	rm -rf $(O)
